import { contextBridge, ipcRenderer } from 'electron'

contextBridge.exposeInMainWorld('api', {
  shell: {
    openExternal: (url: string) => ipcRenderer.invoke('shell:open-external', url),
    openPrint: (factuurId: string) => ipcRenderer.invoke('shell:open-print', factuurId),
  },
  auth: {
    setupStatus: () => ipcRenderer.invoke('auth:setup-status'),
    setup: (data: unknown) => ipcRenderer.invoke('auth:setup', data),
    login: (email: string, wachtwoord: string) => ipcRenderer.invoke('auth:login', email, wachtwoord),
  },
  klanten: {
    list: (params?: unknown) => ipcRenderer.invoke('klanten:list', params),
    get: (id: string) => ipcRenderer.invoke('klanten:get', id),
    create: (data: unknown) => ipcRenderer.invoke('klanten:create', data),
    update: (id: string, data: unknown) => ipcRenderer.invoke('klanten:update', id, data),
    delete: (id: string) => ipcRenderer.invoke('klanten:delete', id),
  },
  facturen: {
    list: (params?: unknown) => ipcRenderer.invoke('facturen:list', params),
    get: (id: string) => ipcRenderer.invoke('facturen:get', id),
    create: (data: unknown) => ipcRenderer.invoke('facturen:create', data),
    update: (id: string, data: unknown) => ipcRenderer.invoke('facturen:update', id, data),
    delete: (id: string) => ipcRenderer.invoke('facturen:delete', id),
    verstuur: (id: string, data: unknown) => ipcRenderer.invoke('facturen:verstuur', id, data),
    downloadPdf: (id: string) => ipcRenderer.invoke('facturen:downloadPdf', id),
    maakTermijnFacturen: () => ipcRenderer.invoke('facturen:maakTermijnFacturen'),
    maakCreditnota: (id: string) => ipcRenderer.invoke('facturen:maakCreditnota', id),
    stuurHerinneringen: () => ipcRenderer.invoke('facturen:stuurHerinneringen'),
  },
  offertes: {
    list: (params?: unknown) => ipcRenderer.invoke('offertes:list', params),
    get: (id: string) => ipcRenderer.invoke('offertes:get', id),
    create: (data: unknown) => ipcRenderer.invoke('offertes:create', data),
    update: (id: string, data: unknown) => ipcRenderer.invoke('offertes:update', id, data),
    delete: (id: string) => ipcRenderer.invoke('offertes:delete', id),
  },
  inkomen: {
    list: (params?: unknown) => ipcRenderer.invoke('inkomen:list', params),
    create: (data: unknown) => ipcRenderer.invoke('inkomen:create', data),
    update: (id: string, data: unknown) => ipcRenderer.invoke('inkomen:update', id, data),
    delete: (id: string) => ipcRenderer.invoke('inkomen:delete', id),
  },
  uitgaven: {
    list: (params?: unknown) => ipcRenderer.invoke('uitgaven:list', params),
    create: (data: unknown) => ipcRenderer.invoke('uitgaven:create', data),
    update: (id: string, data: unknown) => ipcRenderer.invoke('uitgaven:update', id, data),
    delete: (id: string) => ipcRenderer.invoke('uitgaven:delete', id),
    uploadBon: (data: unknown) => ipcRenderer.invoke('uitgaven:uploadBon', data),
    openBon: (data: unknown) => ipcRenderer.invoke('uitgaven:openBon', data),
    scanBon: (data: unknown) => ipcRenderer.invoke('uitgaven:scanBon', data),
  },
  categorien: {
    list: () => ipcRenderer.invoke('categorien:list'),
    create: (data: unknown) => ipcRenderer.invoke('categorien:create', data),
    update: (id: string, data: unknown) => ipcRenderer.invoke('categorien:update', id, data),
    delete: (id: string) => ipcRenderer.invoke('categorien:delete', id),
  },
  uren: {
    list: (params?: unknown) => ipcRenderer.invoke('uren:list', params),
    create: (data: unknown) => ipcRenderer.invoke('uren:create', data),
    update: (id: string, data: unknown) => ipcRenderer.invoke('uren:update', id, data),
    delete: (id: string) => ipcRenderer.invoke('uren:delete', id),
    factuurAanmaken: (data: unknown) => ipcRenderer.invoke('uren:factuurAanmaken', data),
  },
  ritten: {
    list: () => ipcRenderer.invoke('ritten:list'),
    create: (data: unknown) => ipcRenderer.invoke('ritten:create', data),
    update: (id: string, data: unknown) => ipcRenderer.invoke('ritten:update', id, data),
    delete: (id: string) => ipcRenderer.invoke('ritten:delete', id),
    exportCsv: (csv: string) => ipcRenderer.invoke('ritten:exportCsv', csv),
  },
  bank: {
    openBestandDialog: () => ipcRenderer.invoke('bank:openBestandDialog'),
    importeerCsv: (data: unknown) => ipcRenderer.invoke('bank:importeerCsv', data),
  },
  instellingen: {
    get: () => ipcRenderer.invoke('instellingen:get'),
    update: (data: unknown) => ipcRenderer.invoke('instellingen:update', data),
    testEmail: (config: unknown) => ipcRenderer.invoke('instellingen:test-email', config),
    googleAuthUrl: () => ipcRenderer.invoke('instellingen:google-auth-url'),
    googleKoppelen: (code: string) => ipcRenderer.invoke('instellingen:google-koppelen', code),
    googleOntkoppelen: () => ipcRenderer.invoke('instellingen:google-ontkoppelen'),
  },
  agenda: {
    haalAfspraken: (params?: unknown) => ipcRenderer.invoke('agenda:haal-afspraken', params),
  },
  producten: {
    list: () => ipcRenderer.invoke('producten:list'),
    create: (data: unknown) => ipcRenderer.invoke('producten:create', data),
    update: (id: string, data: unknown) => ipcRenderer.invoke('producten:update', id, data),
    delete: (id: string) => ipcRenderer.invoke('producten:delete', id),
  },
  vasteActiva: {
    list: () => ipcRenderer.invoke('vasteActiva:list'),
    create: (data: unknown) => ipcRenderer.invoke('vasteActiva:create', data),
    update: (id: string, data: unknown) => ipcRenderer.invoke('vasteActiva:update', id, data),
    delete: (id: string) => ipcRenderer.invoke('vasteActiva:delete', id),
  },
  audit: {
    list: (factuurId: string) => ipcRenderer.invoke('audit:list', factuurId),
    create: (data: unknown) => ipcRenderer.invoke('audit:create', data),
  },
  app: {
    getAutoStart: () => ipcRenderer.invoke('app:getAutoStart'),
    setAutoStart: (enabled: boolean) => ipcRenderer.invoke('app:setAutoStart', enabled),
    backup: () => ipcRenderer.invoke('app:backup'),
    kiesPdfMap: () => ipcRenderer.invoke('app:kiesPdfMap'),
  },
})
