import { contextBridge, ipcRenderer } from 'electron'

contextBridge.exposeInMainWorld('api', {
  shell: {
    openExternal: (url: string) => ipcRenderer.invoke('shell:open-external', url),
    openPrint: (factuurId: string) => ipcRenderer.invoke('shell:open-print', factuurId),
  },
  auth: {
    setupStatus: () => ipcRenderer.invoke('auth:setup-status'),
    setup: (data: unknown) => ipcRenderer.invoke('auth:setup', data),
    login: (email: string, wachtwoord: string) => ipcRenderer.invoke('auth:login', email, wachtwoord),
  },
  klanten: {
    list: (params?: unknown) => ipcRenderer.invoke('klanten:list', params),
    get: (id: string) => ipcRenderer.invoke('klanten:get', id),
    create: (data: unknown) => ipcRenderer.invoke('klanten:create', data),
    update: (id: string, data: unknown) => ipcRenderer.invoke('klanten:update', id, data),
    delete: (id: string) => ipcRenderer.invoke('klanten:delete', id),
    deleteMetFacturen: (id: string) => ipcRenderer.invoke('klanten:deleteMetFacturen', id),
    aantalFacturen: (id: string) => ipcRenderer.invoke('klanten:aantalFacturen', id),
    overdragenEnVerwijderen: (id: string, naarKlantId: string) => ipcRenderer.invoke('klanten:overdragenEnVerwijderen', id, naarKlantId),
    archiveer: (id: string) => ipcRenderer.invoke('klanten:archiveer', id),
  },
  facturen: {
    list: (params?: unknown) => ipcRenderer.invoke('facturen:list', params),
    get: (id: string) => ipcRenderer.invoke('facturen:get', id),
    create: (data: unknown) => ipcRenderer.invoke('facturen:create', data),
    update: (id: string, data: unknown) => ipcRenderer.invoke('facturen:update', id, data),
    delete: (id: string) => ipcRenderer.invoke('facturen:delete', id),
    deleteAll: () => ipcRenderer.invoke('facturen:deleteAll'),
    duplicate: (id: string) => ipcRenderer.invoke('facturen:duplicate', id),
    verstuur: (id: string, data: unknown) => ipcRenderer.invoke('facturen:verstuur', id, data),
    downloadPdf: (id: string) => ipcRenderer.invoke('facturen:downloadPdf', id),
    maakTermijnFacturen: () => ipcRenderer.invoke('facturen:maakTermijnFacturen'),
    maakCreditnota: (id: string) => ipcRenderer.invoke('facturen:maakCreditnota', id),
    stuurHerinneringen: () => ipcRenderer.invoke('facturen:stuurHerinneringen'),
    stuurHerinnering: (id: string) => ipcRenderer.invoke('facturen:stuurHerinnering', id),
    importeerHistorisch: (data: unknown) => ipcRenderer.invoke('facturen:importeerHistorisch', data),
    onbetaaldeMeldingen: () => ipcRenderer.invoke('facturen:onbetaaldeMeldingen'),
    scanPdf: (data: { pad: string }) => ipcRenderer.invoke('facturen:scanPdf', data),
    scanPdfLokaal: (data: { pad: string }) => ipcRenderer.invoke('facturen:scanPdfLokaal', data),
    kiesBestanden: () => ipcRenderer.invoke('facturen:kiesBestanden'),
    openBronBestand: (id: string) => ipcRenderer.invoke('facturen:openBronBestand', id),
  },
  offertes: {
    list: (params?: unknown) => ipcRenderer.invoke('offertes:list', params),
    get: (id: string) => ipcRenderer.invoke('offertes:get', id),
    create: (data: unknown) => ipcRenderer.invoke('offertes:create', data),
    update: (id: string, data: unknown) => ipcRenderer.invoke('offertes:update', id, data),
    delete: (id: string) => ipcRenderer.invoke('offertes:delete', id),
    verstuur: (id: string, data: unknown) => ipcRenderer.invoke('offertes:verstuur', id, data),
  },
  inkomen: {
    list: (params?: unknown) => ipcRenderer.invoke('inkomen:list', params),
    create: (data: unknown) => ipcRenderer.invoke('inkomen:create', data),
    update: (id: string, data: unknown) => ipcRenderer.invoke('inkomen:update', id, data),
    delete: (id: string) => ipcRenderer.invoke('inkomen:delete', id),
    deleteAll: () => ipcRenderer.invoke('inkomen:deleteAll'),
  },
  uitgaven: {
    list: (params?: unknown) => ipcRenderer.invoke('uitgaven:list', params),
    create: (data: unknown) => ipcRenderer.invoke('uitgaven:create', data),
    update: (id: string, data: unknown) => ipcRenderer.invoke('uitgaven:update', id, data),
    delete: (id: string) => ipcRenderer.invoke('uitgaven:delete', id),
    deleteAll: () => ipcRenderer.invoke('uitgaven:deleteAll'),
    uploadBon: (data: unknown) => ipcRenderer.invoke('uitgaven:uploadBon', data),
    openBon: (data: unknown) => ipcRenderer.invoke('uitgaven:openBon', data),
    scanBon: (data: { bonPad: string; lokaal?: boolean }) => ipcRenderer.invoke('uitgaven:scanBon', data),
    kiesBon: () => ipcRenderer.invoke('uitgaven:kiesBon'),
  },
  categorien: {
    list: () => ipcRenderer.invoke('categorien:list'),
    create: (data: unknown) => ipcRenderer.invoke('categorien:create', data),
    update: (id: string, data: unknown) => ipcRenderer.invoke('categorien:update', id, data),
    delete: (id: string) => ipcRenderer.invoke('categorien:delete', id),
  },
  uren: {
    list: (params?: unknown) => ipcRenderer.invoke('uren:list', params),
    create: (data: unknown) => ipcRenderer.invoke('uren:create', data),
    update: (id: string, data: unknown) => ipcRenderer.invoke('uren:update', id, data),
    delete: (id: string) => ipcRenderer.invoke('uren:delete', id),
    factuurAanmaken: (data: unknown) => ipcRenderer.invoke('uren:factuurAanmaken', data),
  },
  ritten: {
    list: () => ipcRenderer.invoke('ritten:list'),
    create: (data: unknown) => ipcRenderer.invoke('ritten:create', data),
    update: (id: string, data: unknown) => ipcRenderer.invoke('ritten:update', id, data),
    delete: (id: string) => ipcRenderer.invoke('ritten:delete', id),
    exportCsv: (csv: string) => ipcRenderer.invoke('ritten:exportCsv', csv),
    doorbelasten: (data: unknown) => ipcRenderer.invoke('ritten:doorbelasten', data),
  },
  crediteuren: {
    list: (params?: unknown) => ipcRenderer.invoke('crediteuren:list', params),
    create: (data: unknown) => ipcRenderer.invoke('crediteuren:create', data),
    update: (id: string, data: unknown) => ipcRenderer.invoke('crediteuren:update', id, data),
    delete: (id: string) => ipcRenderer.invoke('crediteuren:delete', id),
  },
  klantNotities: {
    list: (klantId: string) => ipcRenderer.invoke('klanten:notities:list', klantId),
    create: (data: unknown) => ipcRenderer.invoke('klanten:notities:create', data),
    delete: (id: string) => ipcRenderer.invoke('klanten:notities:delete', id),
  },
  rapport: {
    exportBtw: (params: unknown) => ipcRenderer.invoke('rapport:exportBtw', params),
  },
  bank: {
    openBestandDialog: () => ipcRenderer.invoke('bank:openBestandDialog'),
    importeerCsv: (data: unknown) => ipcRenderer.invoke('bank:importeerCsv', data),
    leesRuweData: (filePath: string) => ipcRenderer.invoke('bank:leesRuweData', filePath),
    importeerMetMapping: (data: unknown) => ipcRenderer.invoke('bank:importeerMetMapping', data),
    controleerDuplicaten: () => ipcRenderer.invoke('bank:controleerDuplicaten'),
    zoekFactuurMatch: (params: unknown) => ipcRenderer.invoke('bank:zoekFactuurMatch', params),
    koppelAanFactuur: (params: unknown) => ipcRenderer.invoke('bank:koppelAanFactuur', params),
    koppelAanMeerdereFacturen: (params: unknown) => ipcRenderer.invoke('bank:koppelAanMeerdereFacturen', params),
    ontkoppelVanFacturen: (inkomstenId: string) => ipcRenderer.invoke('bank:ontkoppelVanFacturen', inkomstenId),
  },
  offertes_extra: {
    checkVerlopen: () => ipcRenderer.invoke('offertes:checkVerlopen'),
  },
  instellingen: {
    get: () => ipcRenderer.invoke('instellingen:get'),
    update: (data: unknown) => ipcRenderer.invoke('instellingen:update', data),
    testEmail: (config: unknown) => ipcRenderer.invoke('instellingen:test-email', config),
    googleAuthUrl: () => ipcRenderer.invoke('instellingen:google-auth-url'),
    googleKoppelen: () => ipcRenderer.invoke('instellingen:google-koppelen'),
    googleOntkoppelen: () => ipcRenderer.invoke('instellingen:google-ontkoppelen'),
  },
  agenda: {
    haalAfspraken: (params?: unknown) => ipcRenderer.invoke('agenda:haal-afspraken', params),
    haalKalenders: () => ipcRenderer.invoke('agenda:haal-kalenders'),
    maakAfspraak: (data: unknown) => ipcRenderer.invoke('agenda:maak-afspraak', data),
    maakFacturenVanAfspraak: (data: unknown) => ipcRenderer.invoke('agenda:maak-facturen-van-afspraak', data),
  },
  producten: {
    list: () => ipcRenderer.invoke('producten:list'),
    create: (data: unknown) => ipcRenderer.invoke('producten:create', data),
    update: (id: string, data: unknown) => ipcRenderer.invoke('producten:update', id, data),
    delete: (id: string) => ipcRenderer.invoke('producten:delete', id),
  },
  vasteActiva: {
    list: () => ipcRenderer.invoke('vasteActiva:list'),
    create: (data: unknown) => ipcRenderer.invoke('vasteActiva:create', data),
    update: (id: string, data: unknown) => ipcRenderer.invoke('vasteActiva:update', id, data),
    delete: (id: string) => ipcRenderer.invoke('vasteActiva:delete', id),
  },
  audit: {
    list: (factuurId: string) => ipcRenderer.invoke('audit:list', factuurId),
    create: (data: unknown) => ipcRenderer.invoke('audit:create', data),
  },
  app: {
    getAutoStart: () => ipcRenderer.invoke('app:getAutoStart'),
    setAutoStart: (enabled: boolean) => ipcRenderer.invoke('app:setAutoStart', enabled),
    backup: () => ipcRenderer.invoke('app:backup'),
    kiesPdfMap: () => ipcRenderer.invoke('app:kiesPdfMap'),
    exporteerData: () => ipcRenderer.invoke('app:exporteerData'),
    exporteerExcel: (jaar: number) => ipcRenderer.invoke('app:exporteerExcel', jaar),
    exportPdfArchief: (jaar: number) => ipcRenderer.invoke('app:exportPdfArchief', jaar),
    installUpdate: () => ipcRenderer.invoke('app:installUpdate'),
  },
  mollie: {
    maakBetaalLink: (factuurId: string) => ipcRenderer.invoke('mollie:maakBetaalLink', factuurId),
    checkBetalingStatus: (factuurId: string) => ipcRenderer.invoke('mollie:checkBetalingStatus', factuurId),
  },
  factuurSjablonen: {
    list: () => ipcRenderer.invoke('factuurSjablonen:list'),
    create: (data: unknown) => ipcRenderer.invoke('factuurSjablonen:create', data),
    delete: (id: string) => ipcRenderer.invoke('factuurSjablonen:delete', id),
  },
  documenten: {
    list: (params: unknown) => ipcRenderer.invoke('documenten:list', params),
    upload: (params: unknown) => ipcRenderer.invoke('documenten:upload', params),
    open: (id: string) => ipcRenderer.invoke('documenten:open', id),
    delete: (id: string) => ipcRenderer.invoke('documenten:delete', id),
  },
  updates: {
    onBeschikbaar: (cb: () => void) => ipcRenderer.on('update:beschikbaar', cb),
    onGedownload: (cb: () => void) => ipcRenderer.on('update:gedownload', cb),
    verwijderListeners: () => {
      ipcRenderer.removeAllListeners('update:beschikbaar')
      ipcRenderer.removeAllListeners('update:gedownload')
    },
    installeer: () => ipcRenderer.invoke('app:installUpdate'),
  },
  bank2: {
    onNieuwBestand: (cb: (data: { pad: string; naam: string }) => void) => ipcRenderer.on('bank:nieuw-bestand', (_e, d) => cb(d)),
    verwijderListeners: () => ipcRenderer.removeAllListeners('bank:nieuw-bestand'),
  },
})
